name: fletcher
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pandas>=1
  - pyarrow>=0.17
  - numba>=0.49
  - numpydoc
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  - setuptools-scm
  - pip
  - codecov
  - six
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - pre_commit
  - dask
  - asv
