jobs:
    win:
      name: "Windwos Py${{ matrix.PYTHON_VERSION }} - ${{ matrix.UPSTREAM_DEV }}"
      runs-on: windows-latest
      env:
        CI: True
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      strategy:
        fail-fast: false
        matrix:
          PYTHON_VERSION: ['3.6', '3.7', '3.8']
          UPSTREAM_DEV: ['default']
          include:
            - UPSTREAM_DEV: 'nightlies'
              PYTHON_VERSION: '3.8'
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2
        - name: Setup conda
          uses: s-weigand/setup-conda@v1
          with:
            update-conda: true
            python-version: ${{ matrix.PYTHON_VERSION }}
            conda-channels: conda-forge, anaconda
        - run: conda --version
        - run: conda config --show channels
        - run: which python
        # - name: Run CI
        #   shell: bash -l {0}
        #   run: ./ci/circle_build_linux.sh ${{ matrix.PYTHON_VERSION }} ${{ matrix.UPSTREAM_DEV }}
